<a href="https://colab.research.google.com/github/Umoboho/Robotics/blob/main/Matrices_and_Trig_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import numpy.linalg as npl
import pandas as pd

Inputing the Denavit Hartenberg parameters of the system

In [ ]:
#data
h_data = [[-90,-90,169.77,64.2],
          [90,0,0,305],
          [-90,90,0,0],
          [0.01,-90,-222.63,0],
          [0.01,90,0,0],
          [0.01,0,-36.25,0]]
joints = len(h_data)

In [ ]:
h_param = []

for data in h_data:
  theta,alpha,dz,rx = tuple(data)
  h_param.append([np.radians(float(theta)),np.radians(float(alpha)),float(dz),float(rx)]) 

h_df = pd.DataFrame (h_param, columns = ['theta','alpha','d','r'])
print (h_df)

[[-1.5707963267948966, -1.5707963267948966, 169.77, 64.2], [1.5707963267948966, 0.0, 0.0, 305.0], [-1.5707963267948966, 1.5707963267948966, 0.0, 0.0], [0.00017453292519943296, -1.5707963267948966, -222.63, 0.0], [0.00017453292519943296, 1.5707963267948966, 0.0, 0.0], [0.00017453292519943296, 0.0, -36.25, 0.0]]
      theta     alpha       d      r
0 -1.570796 -1.570796  169.77   64.2
1  1.570796  0.000000    0.00  305.0
2 -1.570796  1.570796    0.00    0.0
3  0.000175 -1.570796 -222.63    0.0
4  0.000175  1.570796    0.00    0.0
5  0.000175  0.000000  -36.25    0.0


Calculating the Homogenous transformation matrix for each joint from origin to nth joint

In [ ]:
dh_joints = []
for joint in range(joints):
  theta,alpha,dz,rx = (h_param[joint][0],h_param[joint][1],h_param[joint][2],h_param[joint][3])
  print(theta,alpha,dz,rx)
  H = [[np.cos(theta),-(np.sin(theta)*np.cos(alpha)),np.sin(theta)*np.sin(alpha),rx*np.cos(theta)],
       [np.sin(theta),np.cos(theta)*np.cos(alpha),-(np.cos(theta)*np.sin(alpha)),rx*np.sin(theta)],
       [0,np.sin(alpha),np.cos(alpha),dz],
       [0,0,0,1]]
  dh_joints.append(H)

for dh in dh_joints:
  print(np.around(np.matrix(dh),2))
  


-1.5707963267948966 -1.5707963267948966 169.77 64.2
1.5707963267948966 0.0 0.0 305.0
-1.5707963267948966 1.5707963267948966 0.0 0.0
0.00017453292519943296 -1.5707963267948966 -222.63 0.0
0.00017453292519943296 1.5707963267948966 0.0 0.0
0.00017453292519943296 0.0 -36.25 0.0
[[  0.     0.     1.     0.  ]
 [ -1.     0.     0.   -64.2 ]
 [  0.    -1.     0.   169.77]
 [  0.     0.     0.     1.  ]]
[[  0.  -1.   0.   0.]
 [  1.   0.  -0. 305.]
 [  0.   0.   1.   0.]
 [  0.   0.   0.   1.]]
[[ 0.  0. -1.  0.]
 [-1.  0. -0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]]
[[   1.     -0.     -0.      0.  ]
 [   0.      0.      1.      0.  ]
 [   0.     -1.      0.   -222.63]
 [   0.      0.      0.      1.  ]]
[[ 1. -0.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]]
[[  1.    -0.     0.     0.  ]
 [  0.     1.    -0.     0.  ]
 [  0.     0.     1.   -36.25]
 [  0.     0.     0.     1.  ]]


In [ ]:
hw_0 = np.matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

h0_1 = np.matrix([[np.cos(h_param[0][0]),-(np.sin(h_param[0][0])*np.cos(h_param[0][1])),np.sin(h_param[0][0])*np.sin(h_param[0][1]),h_param[0][3]*np.cos(h_param[0][0])],
                  [np.sin(h_param[0][0]),np.cos(h_param[0][0])*np.cos(h_param[0][1]),-(np.cos(h_param[0][0])*np.sin(h_param[0][1])),h_param[0][3]*np.sin(h_param[0][0])],
                  [0,np.sin(h_param[0][1]),np.cos(h_param[0][1]),h_param[0][2]],
                  [0,0,0,1]])
print(np.around(h0_1,3))
h1_2 = np.matrix([[np.cos(h_param[1][0]),-(np.sin(h_param[1][0])*np.cos(h_param[1][1])),np.sin(h_param[1][0])*np.sin(h_param[1][1]),h_param[1][3]*np.cos(h_param[1][0])],
                  [np.sin(h_param[1][0]),np.cos(h_param[1][0])*np.cos(h_param[1][1]),-(np.cos(h_param[1][0])*np.sin(h_param[1][1])),h_param[1][3]*np.sin(h_param[1][0])],
                  [0,np.sin(h_param[1][1]),np.cos(h_param[1][1]),h_param[1][2]],
                  [0,0,0,1]])

h0_2 = np.dot(h0_1,h1_2)
print(np.around(h0_2,3))

h2_3 = np.matrix([[np.cos(h_param[2][0]),-(np.sin(h_param[2][0])*np.cos(h_param[2][1])),np.sin(h_param[2][0])*np.sin(h_param[2][1]),h_param[2][3]*np.cos(h_param[2][0])],
                  [np.sin(h_param[2][0]),np.cos(h_param[2][0])*np.cos(h_param[2][1]),-(np.cos(h_param[2][0])*np.sin(h_param[2][1])),h_param[2][3]*np.sin(h_param[2][0])],
                  [0,np.sin(h_param[2][1]),np.cos(h_param[2][1]),h_param[2][2]],
                  [0,0,0,1]])

h0_3 = np.dot(h0_2,h2_3)
print(np.around(h0_3,3))

h3_4 = np.matrix([[np.cos(h_param[3][0]),-(np.sin(h_param[3][0])*np.cos(h_param[3][1])),np.sin(h_param[3][0])*np.sin(h_param[3][1]),h_param[3][3]*np.cos(h_param[3][0])],
                  [np.sin(h_param[3][0]),np.cos(h_param[3][0])*np.cos(h_param[3][1]),-(np.cos(h_param[3][0])*np.sin(h_param[3][1])),h_param[3][3]*np.sin(h_param[3][0])],
                  [0,np.sin(h_param[3][1]),np.cos(h_param[3][1]),h_param[3][2]],
                  [0,0,0,1]])

h0_4 = np.dot(h0_3,h3_4)
print(np.around(h0_4,3))

h4_5 = np.matrix([[np.cos(h_param[4][0]),-(np.sin(h_param[4][0])*np.cos(h_param[4][1])),np.sin(h_param[4][0])*np.sin(h_param[4][1]),h_param[4][3]*np.cos(h_param[4][0])],
                  [np.sin(h_param[4][0]),np.cos(h_param[4][0])*np.cos(h_param[4][1]),-(np.cos(h_param[4][0])*np.sin(h_param[4][1])),h_param[4][3]*np.sin(h_param[4][0])],
                  [0,np.sin(h_param[4][1]),np.cos(h_param[4][1]),h_param[4][2]],
                  [0,0,0,1]])

h0_5 = np.dot(h0_4,h4_5)
print(np.around(h0_5,3))

h5_6 = np.matrix([[np.cos(h_param[5][0]),-(np.sin(h_param[5][0])*np.cos(h_param[5][1])),np.sin(h_param[5][0])*np.sin(h_param[5][1]),h_param[5][3]*np.cos(h_param[5][0])],
                  [np.sin(h_param[5][0]),np.cos(h_param[5][0])*np.cos(h_param[5][1]),-(np.cos(h_param[5][0])*np.sin(h_param[5][1])),h_param[5][3]*np.sin(h_param[5][0])],
                  [0,np.sin(h_param[5][1]),np.cos(h_param[5][1]),h_param[5][2]],
                  [0,0,0,1]])

h0_6 = np.dot(h0_5,h5_6)
print(np.around(h0_6,3))

h6_t = np.matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

[[  0.     0.     1.     0.  ]
 [ -1.     0.     0.   -64.2 ]
 [  0.    -1.     0.   169.77]
 [  0.     0.     0.     1.  ]]
[[   0.     -0.      1.      0.  ]
 [  -0.      1.      0.    -64.2 ]
 [  -1.     -0.      0.   -135.23]
 [   0.      0.      0.      1.  ]]
[[   0.      1.      0.      0.  ]
 [  -1.      0.      0.    -64.2 ]
 [   0.      0.      1.   -135.23]
 [   0.      0.      0.      1.  ]]
[[   0.      0.      1.      0.  ]
 [  -1.      0.      0.    -64.2 ]
 [   0.     -1.      0.   -357.86]
 [   0.      0.      0.      1.  ]]
[[   0.      1.      0.      0.  ]
 [  -1.      0.     -0.    -64.2 ]
 [  -0.      0.      1.   -357.86]
 [   0.      0.      0.      1.  ]]
[[   0.       1.       0.      -0.   ]
 [  -1.       0.      -0.     -64.194]
 [  -0.       0.       1.    -394.11 ]
 [   0.       0.       0.       1.   ]]


Calulating the Homogenous transformation matrix of nth joint to the origin

---



In [ ]:
dh0_n = np.identity(4)
systemframe = np.matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])
toolframe = np.matrix([[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]])

dh0_n = np.dot(dh0_n,systemframe)
for n in range(joints):
  dh0_n = np.dot(dh0_n,np.matrix(dh_joints[n]))
dh0_n = np.dot(dh0_n,toolframe)

dh0_n = np.around(dh0_n, decimals=3, out=None)

print(dh0_n) 

[[   0.       1.       0.      -0.   ]
 [  -1.       0.      -0.     -64.194]
 [  -0.       0.       1.    -394.11 ]
 [   0.       0.       0.       1.   ]]


In [ ]:
hw_t = npl.multi_dot([hw_0,h0_1,h1_2,h2_3,h3_4,h4_5,h5_6,h6_t])
print(np.around(hw_t,2))
x = hw_t[0,-1]
y = hw_t[1,-1]
z = hw_t[2,-1]
roty = np.arctan2(-hw_t[2,0], np.sqrt(np.float_power(hw_t[0,0],2) + np.float_power(hw_t[1,0],2)))
rotx = np.arctan2(hw_t[2,1]/np.cos(roty),hw_t[2,2]/np.cos(roty)) 
rotz = np.arctan2((hw_t[1,0]/np.cos(roty)),(hw_t[0,0]/np.cos(roty)))

print(np.around(x,4))
print(np.around(y,4))
print(np.around(z,4))
print(np.around(np.degrees(rotx),4))
print(np.around(np.degrees(roty),4))
print(np.around(np.degrees(rotz),4))


[[   0.      1.      0.     -0.  ]
 [  -1.      0.     -0.    -64.19]
 [  -0.      0.      1.   -394.11]
 [   0.      0.      0.      1.  ]]
-0.0
-64.1937
-394.11
90.0
0.01
179.98


Calculating the rotatational velocity of each joint based on the velocity of end-effector's linear and rotational velocities of each axis

https://www.w3schools.com/python/numpy/numpy_array_slicing.asp
https://numpy.org/doc/stable/reference/index.html

In [ ]:
#nLinear velocities for jacobian matrix
j1l = np.cross(np.identity(3)[0:3, -2:-1], h0_6[0:3, -1:],axis=0)
j2l = np.cross(h0_2[0:3, -2:-1], h0_6[0:3, -1:] - h0_1[0:3, -1:],axis=0)
j3l = np.cross(h0_3[0:3, -2:-1], h0_6[0:3, -1:] - h0_2[0:3, -1:],axis=0)
j4l = np.cross(h0_4[0:3, -2:-1], h0_6[0:3, -1:] - h0_3[0:3, -1:],axis=0)
j5l = np.cross(h0_5[0:3, -2:-1], h0_6[0:3, -1:] - h0_4[0:3, -1:],axis=0)
j6l = np.cross(h0_6[0:3, -2:-1], h0_6[0:3, -1:] - h0_5[0:3, -1:],axis=0)


NameError: ignored

In [ ]:
#nRotational velocities for jacobian matrix
j1r = np.identity(3)[0:3, -2:-1]
j2r = h0_2[0:3, -2:-1]
j3r = h0_3[0:3, -2:-1]
j4r = h0_4[0:3, -2:-1]
j5r = h0_5[0:3, -2:-1]
j6r = h0_6[0:3, -2:-1]


In [ ]:
#Jacobian matrix
j_matrix = np.matrix([[j1l[0],j2l[0],j3l[0],j4l[0],j5l[0],j6l[0]],
                      [j1l[1],j2l[1],j3l[1],j4l[1],j5l[1],j6l[1]],
                      [j1l[2],j2l[2],j3l[2],j4l[2],j5l[2],j6l[2]],
                      [j1r[0],j2r[0],j3r[0],j4r[0],j5r[0],j6r[0]],
                      [j1r[1],j2r[1],j3r[1],j4r[1],j5r[1],j6r[1]],
                      [j1r[2],j2r[2],j3r[2],j4r[2],j5r[2],j6r[2]]])

print(np.around(j_matrix,1))

In [ ]:
jnl = np.hstack((j1l,j2l,j3l,j4l,j5l,j6l))
jnr = np.hstack((j1r,j2r,j3r,j4r,j5r,j6r))

j_matrix = np.vstack((jnl,jnr))

print(np.around(j_matrix,1))

[[-394.1   -0.    -0.    -0.    -0.    -0. ]
 [   0.   563.9   -0.   258.9    0.     0. ]
 [   0.     0.     0.     0.     0.     0. ]
 [   0.     1.     0.     1.     0.     0. ]
 [   1.     0.     0.     0.    -0.    -0. ]
 [   0.     0.     1.     0.     1.     1. ]]
